"""`setup_path()` must install primary and compatibility ACP launchers.

ACP hosts (Zed, JetBrains, Buzz Desktop) spawn the agent by resolving a command
name against the login-shell PATH. The console scripts generated by the
packaging metadata live inside the install's venv, which is not on that PATH.
`setup_path()` therefore writes the primary `panergos-acp` launcher and keeps
`panergos-acp` as a compatibility alias.

These tests drive the real block out of `scripts/install.sh` rather than
asserting on a copy of it, so the shim cannot drift away from the test.
"""

import re
import shlex
import subprocess
from pathlib import Path
from unittest.mock import patch

INSTALL_SH = Path(__file__).resolve().parent.parent.parent.parent / "scripts" / "install.sh"

ACP_BLOCK = re.compile(
    r'(    rm -f "\$command_link_dir/panergos-acp".*?'
    r'log_success "Installed panergos-acp launcher[^\n]*\n)',
    re.S,
)


def _shell_path(path: Path) -> str:
    """Return a Bash-native path, including when Windows launches WSL Bash."""
    anchor = path if path.is_dir() else path.parent
    result = subprocess.run(
        ["bash", "-c", 'printf "%s" "$PWD"'],
        cwd=anchor,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    translated = result.stdout
    if anchor != path:
        translated = f"{translated.rstrip('/')}/{path.name}"
    return shlex.quote(translated)


def _is_shell_executable(path: Path) -> bool:
    """Check the mode from Bash so DrvFS permissions are interpreted correctly."""
    result = subprocess.run(
        ["bash"],
        input=f"test -x {_shell_path(path)}\n".encode("utf-8"),
        capture_output=True,
        cwd=path.parent,
    )
    return result.returncode == 0


def _extract_acp_shim_block() -> str:
    match = ACP_BLOCK.search(INSTALL_SH.read_text(encoding="utf-8"))
    assert match, (
        "could not locate the panergos-acp launcher block in scripts/install.sh — "
        "if it was renamed, update this test with it"
    )
    return match.group(1)


def _run_block(tmp_path: Path, use_venv: str) -> Path:
    """Execute the extracted block with the env vars setup_path() sets."""
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    panergos_bin = tmp_path / "venv" / "bin" / "python"
    panergos_bin.parent.mkdir(parents=True)
    panergos_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    entrypoint = tmp_path / "panergos"
    entrypoint.write_text("#!/bin/sh\n", encoding="utf-8")

    script = (
        "set -e\n"
        f"PANERGOS_BIN={_shell_path(panergos_bin)}\n"
        f"PANERGOS_ENTRYPOINT={_shell_path(entrypoint)}\n"
        f"command_link_dir={_shell_path(command_link_dir)}\n"
        f"command_link_display_dir={_shell_path(command_link_dir)}\n"
        f"USE_VENV={use_venv}\n"
        "log_success(){ :; }\n" + _extract_acp_shim_block()
    )
    result = subprocess.run(
        ["bash"],
        input=script.encode("utf-8"),
        capture_output=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, (
        f"acp shim block failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    return command_link_dir / "panergos-acp"


def test_venv_install_writes_executable_acp_launcher(tmp_path):
    shim = _run_block(tmp_path, "true")
    assert shim.is_file()
    assert _is_shell_executable(shim), "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    # The launcher must dispatch to the ACP subcommand, otherwise the host gets
    # an interactive CLI on stdio and the handshake never completes.
    assert re.search(r'exec .*\bacp\b', text), text


def test_non_venv_install_writes_acp_launcher(tmp_path):
    shim = _run_block(tmp_path, "false")
    text = shim.read_text(encoding="utf-8")
    assert re.search(r'exec .*\bacp\b', text), text


def test_install_writes_primary_panergos_acp_launcher(tmp_path):
    compatibility_shim = _run_block(tmp_path, "true")
    primary_shim = compatibility_shim.with_name("panergos-acp")

    assert primary_shim.is_file()
    assert _is_shell_executable(primary_shim)
    assert primary_shim.read_bytes() == compatibility_shim.read_bytes()


def test_acp_launcher_does_not_follow_a_symlink_into_the_venv(tmp_path):
    """Guards the #21454 failure mode for the new launcher.

    An older install could leave `panergos-acp` as a symlink to the venv console
    script. Without the `rm -f`, `cat >` follows it and overwrites that script
    with a shim that then execs itself.
    """
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    console_script = tmp_path / "venv" / "bin" / "panergos-acp"
    console_script.parent.mkdir(parents=True)
    marker = "#!/usr/bin/env python\n# real console script\n"
    console_script.write_text(marker, encoding="utf-8")

    shim_path = command_link_dir / "panergos-acp"
    shim_path.symlink_to(console_script)
    assert shim_path.is_symlink()

    panergos_bin = tmp_path / "venv" / "bin" / "python"
    panergos_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    entrypoint = tmp_path / "panergos"
    entrypoint.write_text("#!/bin/sh\n", encoding="utf-8")

    script = (
        "set -e\n"
        f"PANERGOS_BIN={_shell_path(panergos_bin)}\n"
        f"PANERGOS_ENTRYPOINT={_shell_path(entrypoint)}\n"
        f"command_link_dir={_shell_path(command_link_dir)}\n"
        f"command_link_display_dir={_shell_path(command_link_dir)}\n"
        "USE_VENV=true\n"
        "log_success(){ :; }\n" + _extract_acp_shim_block()
    )
    result = subprocess.run(
        ["bash"],
        input=script.encode("utf-8"),
        capture_output=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, result.stderr

    assert console_script.read_text(encoding="utf-8") == marker, (
        "venv/bin/panergos-acp was overwritten — symlink-stomp regression (#21454)"
    )
    assert not shim_path.is_symlink(), (
        "command_link_dir/panergos-acp must be replaced with a regular file"
    )


# ---------------------------------------------------------------------------
# panergos-agent launcher regression (#74819)
# ---------------------------------------------------------------------------

PANERGOS_AGENT_BLOCK = re.compile(
    r'(rm -f "\$command_link_dir/panergos-agent".*?'
    r'log_success "Installed panergos-agent launcher[^\n]*\n)',
    re.S,
)


def _extract_panergos_agent_shim_block() -> str:
    match = PANERGOS_AGENT_BLOCK.search(INSTALL_SH.read_text(encoding="utf-8"))
    assert match, (
        "could not locate the panergos-agent launcher block in scripts/install.sh — "
        "if it was renamed, update this test with it"
    )
    return match.group(1)


def _run_panergos_agent_block(tmp_path: Path, use_venv: str) -> Path | None:
    """Execute the extracted panergos-agent block with the env vars setup_path() sets."""
    if use_venv == "false":
        # --no-venv: panergos-agent is NOT installed by this block (handled
        # elsewhere), so there's nothing to test here.
        return None

    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    panergos_bin = tmp_path / "venv" / "bin" / "python"
    panergos_bin.parent.mkdir(parents=True)
    panergos_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    install_dir = tmp_path / "install"
    install_dir.mkdir()

    script = (
        "set -e\n"
        f"PANERGOS_BIN={_shell_path(panergos_bin)}\n"
        f"INSTALL_DIR={_shell_path(install_dir)}\n"
        f"command_link_dir={_shell_path(command_link_dir)}\n"
        f"command_link_display_dir={_shell_path(command_link_dir)}\n"
        f"USE_VENV={use_venv}\n"
        "log_success(){ :; }\n" + _extract_panergos_agent_shim_block()
    )
    result = subprocess.run(
        ["bash"],
        input=script.encode("utf-8"),
        capture_output=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, (
        f"panergos-agent shim block failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    return command_link_dir / "panergos-agent"


def test_venv_install_writes_executable_panergos_agent_launcher(tmp_path):
    """venv install must write a user-executable panergos-agent launcher."""
    shim = _run_panergos_agent_block(tmp_path, "true")
    assert shim is not None
    assert shim.is_file()
    assert _is_shell_executable(shim), "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    assert "run_agent.py" in text, "panergos-agent must dispatch to run_agent.py"


def test_panergos_agent_launcher_cleanup_on_uninstall(tmp_path):
    """Uninstall removes panergos-agent alongside primary and compatibility shims."""
    from panergos_cli.uninstall import remove_wrapper_script

    # Simulate a panergos-agent wrapper in the user-local location
    local_shim = tmp_path / ".local" / "bin" / "panergos-agent"
    local_shim.parent.mkdir(parents=True)
    local_shim.write_text("#!/usr/bin/env bash\nexec panergos-agent\n", encoding="utf-8")

    with patch.object(Path, "home", return_value=tmp_path):
        removed = remove_wrapper_script()

    assert local_shim in removed, "local panergos-agent wrapper must be removed"
